name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cuda-toolkit=12.8
  - ffmpeg
  - gdown
  - ipykernel
  - jupyterlab
  - plyfile
  - python=3.10
  - pip=25.2
  - tqdm
  - gcc=13.4
